# Generated by Django 3.0.7 on 2020-07-05 00:42

from django.db import migrations, models
import django.utils.timezone
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200626_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=post.models.user_directory_path, verbose_name='Picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='post.Tag'),
        ),
    ]
