# Generated by Django 3.0.7 on 2020-08-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200717_2227'),
        ('notifications', '0003_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post', to='post.Post'),
        ),
    ]
