# Generated by Django 3.0.7 on 2020-08-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200810_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[('Like', 1), ('Comment', 2), ('Follow', 3)]),
        ),
    ]
